FROM node:16-alpine

ENV NODE_ENV development

# Set working directory
WORKDIR /app

# Add turborepo
RUN yarn global add turbo

# Copy the entire application
COPY . .

# Install app dependencies
RUN yarn install

CMD ["yarn", "dev"]
